[package]
name    = "bc-kdf"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.9.1"
cmac   = "0.8.0"
hkdf   = "0.13.0"
sha2   = "0.11.0"
sha3   = "0.12.0"
cipher = "0.5.2"
digest = "0.11.3"


[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
hex       = "0.4"

[[bench]]
name    = "kdf_benchmark"
harness = false